inherit_from: .rubocop_todo.yml

require: rubocop-rails

Metrics/LineLength:
  Max: 150

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']

Layout/EndOfLine:
   Enabled: False

Style/MultilineMethodCallIndentation:
  EnforcedStyle: aligned

Style/FrozenStringLiteralComment:
  Enabled: false
